name: mt_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - mitofinder=1.4.1
  - mafft
  - bwa
  - samtools
  - bcftools
  - blast
  - spades
  - megahit
  - trnascan-se
  - arwen
